config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
# frozen_string_literal: true

namespace :app_proxy do
  root action: 'index'
  # simple routes without a specified controller will go to AppProxyController

  # more complex routes will go to controllers in the AppProxy namespace
  #   resources :reviews
  # GET /app_proxy/reviews will now be routed to
  # AppProxy::ReviewsController#index, for example
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/search_products' => 'home#search_products'
  get '/search_variants' => 'home#search_variants'
  get '/search_collections' => 'home#search_collections'
  get '/api/product' => 'api#product'
  get '/api/multi-products' => 'api#multi_products'
  get '/api/filter_options' => 'api#filter_options'
  post '/api/draft-order' => 'api#draft_order'
  post '/api/cart' => 'api#cart'

  resources :installation
  resources :rules
  resources :suppliers do
    member do
      get :status
      get :get_sub_brands
    end
  end
  resources :products do
    collection do
      get :missing
    end
  end
  resources :variants
  resources :orders
  resources :purchase_orders do
    collection do
      get :create_po
    end
    member do
      post :append_draft_order
      put :complete_draft_order
    end
  end
  resources :purchase_order_items do
    member do
      get :send_invoice
      get :download_pdf
      get :render_pdf
    end
  end
  resource :settings, only: %i(show update)
end

app/models/purchase_order_item.rb
require "render_anywhere"

class PurchaseOrderItem < ApplicationRecord
	belongs_to :shop, optional: true
	belongs_to :purchase_order
	belongs_to :vendor, optional: true
	has_many :purchase_order_line_items, dependent: :destroy

  validates :vendor_id, uniqueness: { scope: :purchase_order_id }
    
	enum status: { 
    opened: 0,
    invoice_sent: 1,
    completed: 2,
    declined: 3,
    paused: 4,
    stopped: 5
  }

  include RenderAnywhere

  def po_number(draft_order_name)
    formatted_po = "0000" + self.id.to_s
    formatted_po = formatted_po[(formatted_po.length-4)..(formatted_po.length-1)]
    "#{draft_order_name.gsub('#', '')}-#{formatted_po}"
  end

  def to_pdf(po, draft_order, vendor, cart_json)
    # kit = PDFKit.new( as_html(po, draft_order, vendor, cart_json) )
    kit = PDFKit.new( "https://#{ENV['APP_DOMAIN']}/purchase_order_items/#{self.id}/render_pdf" )
    # kit.to_file("tmp/#{self.po_number(draft_order.name)}.pdf")
    kit.to_pdf
  end

  private

  def as_html(po, draft_order, vendor, cart_json)
    render template: "purchase_order_items/contents",
      layout: "application",
      locals: { po: po, vendor: vendor, po_item: self, draft_order: draft_order, cart_json: cart_json }
  end
end

app/controllers/purchase_order_items_controller.rb
class PurchaseOrderItemsController < ApplicationController
	protect_from_forgery with: :null_session, only: [:download_pdf]
  skip_before_action :verify_authenticity_token, only: [:download_pdf]

	def new
		@po = PurchaseOrder.find(params[:po_id])
		@draft_order = @po.api_data
		@vendor = Vendor.find(params[:vendor_id])
		@po_item = PurchaseOrderItem.new(shop: Shop.first, purchase_order: @po, vendor: @vendor)
		respond_to do |format|
      format.js { render :layout => false }
    end
	end

	def edit
		@po_item = PurchaseOrderItem.find(params[:id])
		@po = @po_item.purchase_order
		@draft_order = @po.api_data
		@vendor = @po_item.vendor
		@cart = Cart.find_by(token: @draft_order.custom_attributes.select{|c_attr| c_attr.key == 'token' }&.first&.value)
		@cart_json = JSON.parse(@cart.full_json) if @cart.present? && @cart.full_json.present?
		respond_to do |format|
      format.js { render :layout => false }
    end
	end

	def create
		@po_item = PurchaseOrderItem.create(po_item_params)
		params[:purchase_order_line_item].each do |po_l_item|
			po_line_item = PurchaseOrderLineItem.new(po_line_item_params(po_l_item))
			po_line_item.purchase_order_item = @po_item
			po_line_item.save!
		end
		flash[:notice] = 'Invoice Preview is created!'
		redirect_to purchase_order_path(id: po_item_params[:purchase_order_id])
	end

	def update
		@po_item = PurchaseOrderItem.find(params[:id])
		@po_item.update po_item_params
		params[:purchase_order_line_item].each do |po_l_item|
			po_line_item = PurchaseOrderLineItem.find_or_create_by(purchase_order_item: @po_item, variant_id: po_line_item_params(po_l_item)[:variant_id])
			# po_line_item = PurchaseOrderLineItem.find(po_line_item_params(po_l_item)[:id])
			po_line_item.update po_line_item_params(po_l_item)
		end
		if ActiveModel::Type::Boolean.new.cast(params[:send_invoice]) || ActiveModel::Type::Boolean.new.cast(params[:preview_invoice])
			if @po_item.purchase_order_line_items.present?
				MessageMailer.with(purchase_order_item_id: params[:id], preview: ActiveModel::Type::Boolean.new.cast(params[:preview_invoice])).send_invoice.deliver_later
				flash[:notice] = 'Purchase Order is approved and invoice is sent!'
			end
		else
			flash[:notice] = 'Invoice Preview is updated!'	
		end
		redirect_to purchase_order_path(id: po_item_params[:purchase_order_id])
	end

	def send_invoice
		@po_item = PurchaseOrderItem.find(params[:id])
		MessageMailer.with(purchase_order_item_id: params[:id]).send_invoice.deliver_later if @po_item.purchase_order_line_items.present?
		respond_to do |format|
      format.js { render :layout => false }
    end
	end

	def download_pdf
		@po_item = PurchaseOrderItem.find(params[:id])
		@po = @po_item.purchase_order
		@draft_order = @po.api_data
		@vendor = @po_item.vendor
		@cart = Cart.find_by(token: @draft_order.custom_attributes.select{|c_attr| c_attr.key == 'token' }&.first&.value)
		@cart_json = JSON.parse(@cart.full_json) if @cart.present? && @cart.full_json.present?
		respond_to do |format|
      format.pdf do
      	send_data @po_item.to_pdf(@po, @draft_order, @vendor, @cart_json)
      end
    end
	end

	def render_pdf
		@po_item = PurchaseOrderItem.find(params[:id])
		@po = @po_item.purchase_order
		@draft_order = @po.api_data
		@vendor = @po_item.vendor
		@cart = Cart.find_by(token: @draft_order.custom_attributes.select{|c_attr| c_attr.key == 'token' }&.first&.value)
		@cart_json = JSON.parse(@cart.full_json) if @cart.present? && @cart.full_json.present?
		render layout: "download"
	end

	private
	def po_item_params
		params.require(:purchase_order_item).permit(:shop_id, :purchase_order_id, :vendor_id, :status, :required_ship_date, :shipping_method, :shipping_address, :notes)
	end

	def po_line_item_params(raw_po_l_item)
		raw_po_l_item.permit(:id, :variant_id, :qty, :unit_cost, :setup_qty, :setup_unit_price, :run_qty, :run_unit_price, :purchase_order_item_id, :freight_cost)
	end

	def send_pdf
    send_file @po_item.to_pdf(@po, @draft_order, @vendor, @cart_json), download_attributes
  end

  def download_attributes
    {
      filename: @po_item.po_number(@draft_order.name) + '.pdf',
      type: "application/pdf",
      disposition: "inline"
    }
  end
end

app/helpers/purchase_order_items_helper.rb
module PurchaseOrderItemsHelper
end

app/views/purchase_order_items/_contents.html.erb
<div class="preview-container">
	<fieldset style="border: 1px solid #000; padding: 15px;">
		<legend>Keepers Collective by Straight Up Purchase order for <%= vendor.company_name %></legend>
		<div class="row">
		  <dt class="col-sm-4 col-12">PO Date:</dt>
		  <dd class="col-sm-8 col-12"><%= po.created_at.strftime('%m/%d/%Y') %></dd>

		  <dt class="col-sm-4 col-12">Project#:</dt>
		  <dd class="col-sm-8 col-12"><%= draft_order.name.gsub('#', '') %></dd>

		  <dt class="col-sm-4 col-12">PO#:</dt>
		  <dd class="col-sm-8 col-12"><%= po_item.po_number(draft_order.name) %></dd>

		  <dt class="col-sm-4 col-12">Account Number:</dt>
		  <dd class="col-sm-8 col-12">337711</dd>

		  <dt class="col-sm-4 col-12">Vendor Name:</dt>
		  <dd class="col-sm-8 col-12"><%= vendor.company_name %></dd>

		  <dt class="col-sm-4 col-12">Ship Date Required:</dt>
		  <dd class="col-sm-8 col-12">Detailed Below</dd>
		</div>
	</fieldset>
	<br>

	<fieldset style="border: 1px solid #000; padding: 15px;">
		<legend>Production Lead Time</legend>
		<div class="row">
			<dt class="col-sm-4 col-12">PRODUCTION LEAD TIME PROMISED:</dt>
		  <dd class="col-sm-8 col-12">5-7 Days</dd>

		  <br>
		  <dt class="col-sm-4 col-12">Production Completion ETA:</dt>
		  <dd class="col-sm-8 col-12">[Date]</dd>
		</div>
	</fieldset>
	<br>

	<fieldset style="border: 1px solid #000; padding: 15px;">
		<legend>Shipping Details</legend>
		<div class="row">
			<dt class="col-sm-4 col-12">SHIPPING METHOD/ACCOUNT #:</dt>
		  <dd class="col-sm-8 col-12">UPS Second Day Air Third Party on UPS 17117E</dd>
		  <br><br>

		  <b>Address Details</b>
		  <% Cart.shipping_attrs.each do |key| %>
				<% next if cart_json['attributes'].present? && cart_json['attributes']['Shipping_ShipType'] == 'Single Address' && (key == 'DropShip_Address_Type' || key == 'Address_Attachment_Type') %>
				<% if cart_json['attributes'].present? && cart_json['attributes'][key].present? %>
					<dt class="col-sm-4 col-12"><%= PurchaseOrder.maps[key.to_sym] %></dt>
					<dd class="col-sm-8 col-12">
						<% if key == 'DropShipAddress_Attachment_File' %><a href="<%= cart_json['attributes'][key] %>" target="_blank" style="word-break: break-all;"><% end %>
							<% if key == 'DeliveryNeededBy_Date' %>
								<%= Time.parse(cart_json['attributes'][key]).strftime('%m-%d-%Y') if cart_json['attributes'][key].present? %>
							<% else %>
								<%= cart_json['attributes'][key]&.gsub('ShipType_SingleAddress_', '') %>
							<% end %>
						<% if key == 'DropShipAddress_Attachment_File' %></a><% end %>
					</dd>
				<% end %>
			<% end %>
		</div>
	</fieldset>
	<br>

	<fieldset style="border: 1px solid #000; padding: 15px;">
		<legend>Product Details</legend>
		<% total_qty = 0 %>
		<% total_costs = 0 %>
		<% total_setup_cost = 0 %>
		<% total_run_charge = 0 %>
		<% total_freight_cost = 0 %>
		<% if po_item.purchase_order_line_items.present? %>
			<% po_item.purchase_order_line_items.each_with_index do |line_item, idx| %>
				<% variant = line_item.variant %>
				<% total_qty += line_item.qty %>
				<% total_costs += line_item.unit_cost * line_item.qty %>
				<% total_costs += line_item.setup_unit_price * line_item.setup_qty %>
				<% total_costs += (line_item.run_unit_price || 0) * (line_item.run_qty || 0) %>
				<% total_costs += line_item.freight_cost %>
				<div>
					<input type="hidden" name="purchase_order_line_item[][id]" value="<%= line_item.id %>">
					<input type="hidden" name="purchase_order_line_item[][variant_id]" value="<%= variant.id %>">
					<input type="hidden" name="send_invoice" value="false">
					<input type="hidden" name="preview_invoice" value="false">
				</div>
				<div class="row">
					<div class="col-12">
						<table class="table table-striped" data-item-table>
							<thead class="thead-dark">
								<tr>
									<th>ITEM #<%= idx + 1 %></th>
									<th>FREIGHT</th>
									<th>QTY</th>
									<th>UNIT COST</th>
									<th>SETUP COST</th>
									<th>TOTAL COST</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>
										Supplier SKU: <b><%= variant.supplier_sku || 'Unkown' %></b><br>
										Supplier Product Name: <b><%= variant.supplier_product_name %></b><br>
										Variant: <b>
											<% if variant.option_1 != 'Default Title' %>
												<%= [variant.option_1, variant.option_2, variant.option_3].reject(&:blank?).join(' x ') %>
											<% end %>
											</b><br>
										KC Item Name: <b><%= variant.product.title %></b><br>
										Brand: <b><%= variant.vender_sub_brands[variant.real_vendor_ids.index(vendor.id)] %></b><br><br>

										<label for="purchase_order_item_shipping_address">
											PRODUCTION LEAD TIME PROMISED: <b>5-7 Days</b><br>
											Production Completion ETA: <b>[DATE]</b>
										</label>
									</td>
									
									<td>$<input type="number" name="purchase_order_line_item[][freight_cost]" value="<%= line_item.freight_cost %>" min="0"></td>

									<td>
										<input type="hidden" name="purchase_order_line_item[][qty]" value="<%= line_item.qty %>">
										<%= line_item.qty %>
									</td>
									<td>
										<input type="hidden" name="purchase_order_line_item[][unit_cost]" value="<%= line_item.unit_cost %>">
										<%= number_to_currency(line_item.unit_cost) %>
									</td>
									<td>
										<input type="hidden" name="purchase_order_line_item[][setup_qty]" value="<%= line_item.setup_qty %>" min="0">
										$<input type="number" name="purchase_order_line_item[][setup_unit_price]" value="<%= line_item.setup_unit_price %>" min="0">
									</td>
									<td data-item-total>
										<%= number_to_currency(total_costs) %>
									</td>
								</tr>
							</tbody>
						</table>
						
						<% if variant.artwork_exist %>
							<b>Artwork Details for <%= variant.supplier_product_name %></b><br>
							Proof Number:  <b><%= variant.proof_number %></b><br>
							Proof Required: Note: <b>Email Proof</b><br>
							Supplier Proof Link: <b><a href="<%= variant.supplier_proof_link %>">View Supplier Proof</a></b><br>
							Keepers Collective Product Link (for additional reference): <b><a href="<%= variant.proof_photo_link %>">View Product Link</a></b><br>
							Logo Name: <b><%= variant.logo_name %></b><br>
							Logo Size: <b><%= variant.logo_size %></b><br>
							Logo Color: <b><%= variant.logo_color %></b><br>
							Decoration Location: <b><%= variant.decoration_location %></b><br>
							Decoration Type: <b><%= variant.decoration_type %></b><br>
							Artwork/Vector Link: <b><a href="<%= variant.artwork_url %>">View Artwork</a></b><br>
						<% else %>
							<b>Artwork Details</b><br>
							None – Blank Product Purchase<br>
						<% end %>
					</div>
				</div>
				<hr>
				<br>
			<% end %>
		<% elsif draft_order.line_items.present? %>
			<% draft_order.line_items.edges.each do |line_item| %>
				<% variant_id = PurchaseOrder.get_variant_id(line_item) %>
				<% line_item = line_item.node %>
				<% variant = Variant.find_by(shopify_id: variant_id) %>
				<% i = 0 %>
				<% if variant.present? && (variant.real_vendor_ids.include? vendor.id) %>
					<% i += 1 %>
					<% price_rule = variant.get_price_rule(line_item.quantity) %>
					<% total_qty += line_item.quantity %>
					<% total_costs += price_rule.item_wholesale_cost * line_item.quantity %>
					<div>
						<input type="hidden" name="purchase_order_line_item[][variant_id]" value="<%= variant.id %>">
					</div>
					<div class="row">
						<div class="col-12">
							<table class="table table-striped" data-item-table>
								<thead class="thead-dark">
									<tr>
										<th>ITEM #<%= i %></th>
										<th>FREIGHT</th>
										<th>QTY</th>
										<th>UNIT COST</th>
										<th>SETUP COST</th>
										<th>TOTAL COST</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>
											Supplier SKU: <b><%= variant.supplier_sku %></b><br>
											Supplier Product Name: <b><%= variant.supplier_product_name %></b><br>
											Variant: <b>
												<% if variant.option_1 != 'Default Title' %>
													<%= [variant.option_1, variant.option_2, variant.option_3].reject(&:blank?).join(' x ') %>
												<% end %>
												</b><br>
											KC Item Name: <b><%= variant.product.title %></b><br>
											Brand: <b><%= variant.vender_sub_brands[variant.real_vendor_ids.index(vendor.id)] %></b><br><br>

											<label for="purchase_order_item_shipping_address">
												PRODUCTION LEAD TIME PROMISED: <b>5-7 Days</b><br>
												Production Completion ETA: <b>[DATE]</b>
											</label>
										</td>
										
										<td>$<input type="number" name="purchase_order_line_item[][freight_cost]" value="0" min="0"></td>

										<td>
											<input type="hidden" name="purchase_order_line_item[][qty]" value="<%= line_item.quantity %>">
											<%= line_item.quantity %>
										</td>
										<td>
											<input type="hidden" name="purchase_order_line_item[][unit_cost]" value="<%= price_rule.item_wholesale_cost %>">
											<%= number_to_currency(price_rule.item_wholesale_cost) %>
										</td>
										<td>
											<input type="hidden" name="purchase_order_line_item[][setup_qty]" value="1" min="0">
											$<input type="number" name="purchase_order_line_item[][setup_unit_price]" value="0" min="0">
										</td>
										<td data-item-total>
											<%= number_to_currency(price_rule.item_wholesale_cost * line_item.quantity) %>
										</td>
									</tr>
								</tbody>
							</table>
							
							<% if variant.artwork_exist %>
								<b>Artwork Details for <%= variant.supplier_product_name %></b><br>
								Proof Number:  <b><%= variant.proof_number %></b><br>
								Proof Required: Note: <b>Email Proof</b><br>
								Supplier Proof Link: <b><a href="<%= variant.supplier_proof_link %>">View Supplier Proof</a></b><br>
								Keepers Collective Product Link (for additional reference): <b><a href="<%= variant.proof_photo_link %>">View Product Link</a></b><br>
								Logo Name: <b><%= variant.logo_name %></b><br>
								Logo Size: <b><%= variant.logo_size %></b><br>
								Logo Color: <b><%= variant.logo_color %></b><br>
								Decoration Location: <b><%= variant.decoration_location %></b><br>
								Decoration Type: <b><%= variant.decoration_type %></b><br>
								Artwork/Vector Link: <b><a href="<%= variant.artwork_url %>">View Artwork</a></b><br>
							<% else %>
								<b>Artwork Details</b><br>
								None – Blank Product Purchase<br>
							<% end %>
						</div>


						<!-- <div class="col-12">
							<table class="table table-striped">
								<thead class="thead-dark">
									<tr>
										<th>SKU</th>
										<th>ITEM</th>
										<th>QTY</th>
										<th>UNIT COST</th>
										<th>TOTAL COST</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td><%#= variant.sku %></td>
										<td>
											<%#= variant.product.title %>
											<%# if variant.option_1 != 'Default Title' %>
												<%#= "(#{[variant.option_1, variant.option_2, variant.option_3].reject(&:blank?).join(' x ')})" %>
											<%# end %>
										</td>
										<td>
											<input type="hidden" name="purchase_order_line_item[][qty]" value="<%#= line_item.quantity %>">
											<%#= line_item.quantity %>
										</td>
										<td>
											<input type="hidden" name="purchase_order_line_item[][unit_cost]" value="<%#= price_rule.item_wholesale_cost %>">
											<%#= number_to_currency(price_rule.item_wholesale_cost) %>
										</td>
										<td>
											<%#= number_to_currency(price_rule.item_wholesale_cost * line_item.quantity) %>
										</td>
									</tr>
								</tbody>
							</table>
							<table class="table table-striped">
								<thead class="thead-dark">
									<tr>
										<th>ARTWORK COSTS</th>
										<th>QTY</th>
										<th>UNIT PRICE</th>
										<th>TOTAL PRICE</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>Setup Cost</td>
										<td><input type="number" name="purchase_order_line_item[][setup_qty]" value="1" min="0"></td>
										<td>$<input type="number" name="purchase_order_line_item[][setup_unit_price]" value="0" min="0"></td>
										<td data-setup-total="0">$0</td>
									</tr>
									<tr>
										<td>Run Charge</td>
										<td><input type="number" name="purchase_order_line_item[][run_qty]" value="<%= line_item.quantity %>" min="0"></td>
										<td>$<input type="number" name="purchase_order_line_item[][run_unit_price]" value="0" min="0"></td>
										<td data-run-total="0">$0</td>
									</tr>
								</tbody>
							</table>
						</div> -->
					</div>
					<hr>
					<br>
				<% end %>	
			<% end %>
		<% end %>
		<div class="row">
			<div class="col-12 col-md-6 offset-md-6">
				<dl class="row">
				  <dt class="col-6">TOTAL UNITS ORDERED</dt>
				  <dd class="col-6 text-right"><%= total_qty %></dd>

				  <dt class="col-6">TOTAL UNIT COSTS</dt>
				  <dd class="col-6 text-right" data-total-costs="<%= total_costs %>"><%= number_to_currency(total_costs) %></dd>

				  <dt class="col-6">TOTAL SETUP COST</dt>
				  <dd class="col-6 text-right" data-total-setup-cost><%= number_to_currency(total_setup_cost) %></dd>

				  <dt class="col-6">TOTAL RUN COSTS</dt>
				  <dd class="col-6 text-right" data-total-run-charge><%= number_to_currency(total_run_charge) %></dd>

					<dt class="col-6">TOTAL FREIGHT COSTS</dt>
				  <dd class="col-6 text-right" data-total-freight-cost><%= number_to_currency(total_run_charge) %></dd>				  

				  <dt class="col-6">ORDER TOTAL</dt>
				  <dd class="col-6 text-right" style="text-decoration: overline;" data-order-total><%= number_to_currency(total_costs + total_setup_cost + total_run_charge + total_freight_cost) %></dd>
				</dl>
			</div>
		</div>
	</fieldset>	
</div>

app/views/purchase_order_items/_form.html.erb
<% http_method = action_name != 'edit' ? :post : :put %>
<% url = action_name != 'edit' ? purchase_order_items_url : purchase_order_item_url(@po_item) %>
<%= form_for @po_item, html: {style: ""}, url: url, method: http_method do |f| %>
	<%= f.hidden_field :shop_id %>
	<%= f.hidden_field :purchase_order_id %>
	<%= f.hidden_field :vendor_id %>
	
	<%= render partial: 'contents', locals: {po: @po, vendor: @vendor, po_item: @po_item, draft_order: @draft_order, cart_json: @cart_json} %>

	<div class="modal-footer">
		<span class="btn btn-success">Send to QuickBooks</span>
		<%= link_to download_pdf_purchase_order_item_path(@po_item, :format => :pdf), method: :get, target: "_blank", class: "btn btn-info download-btn" do %>
	  	Download
  	<% end %>
		<!-- <span class="btn btn-info download-btn" data-invoice-name="<%#= @po_item.po_number(@draft_order.name) %>">Download</span> -->
		<span class="btn btn-light preview-btn">Email Preview</span>
		<span class="btn btn-dark invoice-btn">Approve & Send Purchase Order</span>
    <span class="btn btn-secondary" data-dismiss="modal">Close</span>
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
<% end %>

app/views/purchase_order_items/_po_item_modal.html.erb
<div class="modal fade" id="poItemModal" tabindex="-1" aria-labelledby="poItemModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="poItemModalLabel">Preview Purchase Order</h5>
        <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        
      </div>
    </div>
  </div>
</div>

app/views/purchase_order_items/download_pdf.pdf.erb
<%= render partial: 'contents', locals: {po: @po, vendor: @vendor, po_item: @po_item, draft_order: @draft_order, cart_json: @cart_json} %>

app/views/purchase_order_items/new.js.erb
<% if @po.present? && @draft_order.present? && @vendor.present? %>
$('#poItemModal .modal-body').html("<%= escape_javascript(render partial: 'purchase_order_items/form', locals: {}) %>");
$( "#purchase_order_item_required_ship_date" ).datepicker({
	defaultDate: new Date()
});
$('[name="purchase_order_line_item[][setup_qty]"], [name="purchase_order_line_item[][setup_unit_price]"]').on('change', function() {
	var qty = Math.max(parseInt($(this).closest('tr').find('[name="purchase_order_line_item[][setup_qty]"]').val()), 0);
	var price = Math.max(parseFloat($(this).closest('tr').find('[name="purchase_order_line_item[][setup_unit_price]"]').val()), 0);
	var total = qty * price;
	const formatter = new Intl.NumberFormat('en-US', {
	  style: 'currency',
	  currency: 'USD',
	  minimumFractionDigits: 2
	});
	$(this).closest('tr').find('[data-setup-total]').html(formatter.format(total));
	$(this).closest('tr').find('[data-setup-total]').data('setup-total', total);
	$(this).closest('tr').find('[data-run-total]').html(formatter.format(total));
	$(this).closest('tr').find('[data-run-total]').data('run-total', total);
	var total_costs = parseFloat($('[data-total-costs]').data('total-costs'));
	var setup_total = 0;
	var run_total = 0;
	$('[data-setup-total]').each(function() {
		setup_total += parseFloat($(this).data('setup-total'));
	});
	$('[data-run-total]').each(function() {
		run_total += parseFloat($(this).data('run-total'));
	});
	$('[data-total-setup-cost]').html(formatter.format(setup_total));
	$('[data-total-run-charge]').html(formatter.format(run_total));
	$('[data-order-total]').html(formatter.format(total_costs + setup_total + run_total));
});
$('[name="purchase_order_line_item[][run_qty]"], [name="purchase_order_line_item[][run_unit_price]"]').on('change', function() {
	var qty = Math.max(parseInt($(this).closest('tr').find('[name="purchase_order_line_item[][run_qty]"]').val()), 0);
	var price = Math.max(parseFloat($(this).closest('tr').find('[name="purchase_order_line_item[][run_unit_price]"]').val()), 0);
	var total = qty * price;
	const formatter = new Intl.NumberFormat('en-US', {
	  style: 'currency',
	  currency: 'USD',
	  minimumFractionDigits: 2
	});
	$(this).closest('tr').find('[data-run-total]').html(formatter.format(total));
	$(this).closest('tr').find('[data-run-total]').data('run-total', total);
	var total_costs = parseFloat($('[data-total-costs]').data('total-costs'));
	var setup_total = 0;
	var run_total = 0;
	$('[data-setup-total]').each(function() {
		setup_total += parseFloat($(this).data('setup-total'));
	});
	$('[data-run-total]').each(function() {
		run_total += parseFloat($(this).data('run-total'));
	});
	$('[data-total-setup-cost]').html(formatter.format(setup_total));
	$('[data-total-run-charge]').html(formatter.format(run_total));
	$('[data-order-total]').html(formatter.format(total_costs + setup_total + run_total));
});
$('#poItemModal').modal('show');
<% end %>

app/views/purchase_order_items/render_pdf.html.erb
<%= render partial: 'contents', locals: {po: @po, vendor: @vendor, po_item: @po_item, draft_order: @draft_order, cart_json: @cart_json} %>