config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
# frozen_string_literal: true

namespace :app_proxy do
  root action: 'index'
  # simple routes without a specified controller will go to AppProxyController

  # more complex routes will go to controllers in the AppProxy namespace
  #   resources :reviews
  # GET /app_proxy/reviews will now be routed to
  # AppProxy::ReviewsController#index, for example
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/search_products' => 'home#search_products'
  get '/search_variants' => 'home#search_variants'
  get '/search_collections' => 'home#search_collections'
  get '/api/product' => 'api#product'
  get '/api/multi-products' => 'api#multi_products'
  get '/api/filter_options' => 'api#filter_options'
  post '/api/draft-order' => 'api#draft_order'
  post '/api/cart' => 'api#cart'

  resources :installation
  resources :rules
  resources :suppliers do
    member do
      get :status
      get :get_sub_brands
    end
  end
  resources :products do
    collection do
      get :missing
    end
  end
  resources :variants
  resources :orders
  resources :purchase_orders do
    collection do
      get :create_po
    end
    member do
      post :append_draft_order
      put :complete_draft_order
    end
  end
  resources :purchase_order_items do
    member do
      get :send_invoice
      get :download_pdf
      get :render_pdf
    end
  end
  resource :settings, only: %i(show update)
end

app/views/shared/_collections_modal.haml
.modal.fade#collectionsModal{ tabindex: "-1", "aria-labelledby": "collectionsModalLabel", "aria-hidden": "true"}
  .modal-dialog
    .modal-content
      .modal-header
        %h5.modal-title#collectionsModalLabel Add collections
        %button.close{ type: "button", "data-dismiss": "modal", "aria-label": "Close"}
          %span{ "aria-hidden": "true" } &times;
        
      .modal-body
        %input#search_collections{placeholder: "Search collections", style: "width: 100%;"}
        %ul#search_results
      .modal-footer.justify-content-between
        %span
          %span#selected_count 0
          collections selected
        %div
          %button.btn.btn-secondary{ type: "button", "data-dismiss": "modal"} Close
          %button#add-collection.btn.btn-primary{type: "button"} Add

app/views/shared/_nav.html.erb
<% @nav_str ||= 'Dashboard' %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Keepers Collective Vendor/Product Management App', root_path, class: 'navbar-brand' %>
    <button aria-controls="navbarNav" aria-expanded="false"
      aria-label="Toggle navigation" class="navbar-toggler"
      data-target="#navbarNav" data-toggle="collapse" type="button">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button"
            id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= @nav_str %>
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <% if @nav_str != 'Dashboard' %>
              <%= link_to 'Dashboard', root_path, class: 'dropdown-item' %>
            <% end %>
            <% if @nav_str != 'Vendors' %>
              <%= link_to 'Vendors', suppliers_path, class: 'dropdown-item' %>
            <% end %>
            <% if @nav_str != 'Products' %>
              <%= link_to 'Products', products_path, class: 'dropdown-item' %>
            <% end %>
            <% if @nav_str != 'Orders' %>
              <%= link_to 'Orders', orders_path, class: 'dropdown-item' %>
            <% end %>
            <% if @nav_str != 'PO\'s' %>
              <%= link_to 'PO\'s', purchase_orders_path, class: 'dropdown-item' %>
            <% end %>
            <% if @nav_str != 'Settings' %>
              <%= link_to 'Settings', settings_path, class: 'dropdown-item' %>
            <% end %>
          </div>
        </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_products_modal.haml
.modal.fade#productsModal{ tabindex: "-1", "aria-labelledby": "productsModalLabel", "aria-hidden": "true"}
  .modal-dialog
    .modal-content
      .modal-header
        %h5.modal-title#productsModalLabel Add products
        %button.close{ type: "button", "data-dismiss": "modal", "aria-label": "Close"}
          %span{ "aria-hidden": "true" } &times;
        
      .modal-body
        %input#search_products{placeholder: "Search products"}
        %ul#search_results
      .modal-footer.justify-content-between
        %span
          %span#selected_count 0
          products selected
        %div
          %button.btn.btn-secondary{ type: "button", "data-dismiss": "modal"} Close
          %button#add-product.btn.btn-primary{type: "button"} Add

app/views/shared/_variants_modal.haml
.modal.fade#variantsModal{ tabindex: "-1", "aria-labelledby": "variantsModalLabel", "aria-hidden": "true"}
  .modal-dialog
    .modal-content
      .modal-header
        %h5.modal-title#variantsModalLabel Add products
        %button.close{ type: "button", "data-dismiss": "modal", "aria-label": "Close"}
          %span{ "aria-hidden": "true" } &times;
        
      .modal-body
        %input#search_products{placeholder: "Search products"}
        %ul#search_results
      .modal-footer.justify-content-between
        %span
          %span#selected_count 0
          products selected
        %div
          %button.btn.btn-secondary{ type: "button", "data-dismiss": "modal"} Close
          %button#add-product.btn.btn-primary{type: "button"} Add