config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
# frozen_string_literal: true

namespace :app_proxy do
  root action: 'index'
  # simple routes without a specified controller will go to AppProxyController

  # more complex routes will go to controllers in the AppProxy namespace
  #   resources :reviews
  # GET /app_proxy/reviews will now be routed to
  # AppProxy::ReviewsController#index, for example
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/search_products' => 'home#search_products'
  get '/search_variants' => 'home#search_variants'
  get '/search_collections' => 'home#search_collections'
  get '/api/product' => 'api#product'
  get '/api/multi-products' => 'api#multi_products'
  get '/api/filter_options' => 'api#filter_options'
  post '/api/draft-order' => 'api#draft_order'
  post '/api/cart' => 'api#cart'

  resources :installation
  resources :rules
  resources :suppliers do
    member do
      get :status
      get :get_sub_brands
    end
  end
  resources :products do
    collection do
      get :missing
    end
  end
  resources :variants
  resources :orders
  resources :purchase_orders do
    collection do
      get :create_po
    end
    member do
      post :append_draft_order
      put :complete_draft_order
    end
  end
  resources :purchase_order_items do
    member do
      get :send_invoice
      get :download_pdf
      get :render_pdf
    end
  end
  resource :settings, only: %i(show update)
end

app/models/rule.rb
class Rule < ApplicationRecord
	belongs_to :shop, optional: true
	has_many :conditions, dependent: :destroy
  accepts_nested_attributes_for :conditions,
    reject_if: proc { |c| c[:condition_str].to_s.strip.blank? },
    allow_destroy: true
	has_many :price_levels, dependent: :destroy
  accepts_nested_attributes_for :price_levels,
    reject_if: proc { |c| c[:break_number].to_i < 1 || c[:discount_amount].to_i < 1 },
    allow_destroy: true
	serialize :shopify_ids, Array

  has_many :rule_items, dependent: :destroy
  accepts_nested_attributes_for :rule_items, allow_destroy: true

  validates :name, presence: true, uniqueness: true

	enum rule_type: { 
    product: 0,
    variant: 1,
    collection: 2,
    cart: 3
  }
  enum select_cat: { 
    select_all: 0,
    custom: 1
  }
  enum filter_cat: { 
    filter_custom: 0,
    filter_any: 1,
    filter_all: 2
  }

  def with_defaults
    conditions.build if conditions.blank?
    price_levels.build if price_levels.blank?
    self
  end

  def show_conditions?
    product? && custom? && !filter_custom?
  end

  def show_selected_objects?
    !cart? && custom?
  end
end

app/controllers/rules_controller.rb
class RulesController < AuthenticatedController
  before_action :set_nav
  before_action :set_rule, only: %i(edit update destroy)

  def index
    @rules = Rule.order(created_at: :desc).paginate(page: (params[:page] || 1))
  end

  def new
    @rule = Rule.new.with_defaults
  end

  def create
    rule = Rule.new rule_params
    if rule.save
      redirect_to rules_path
    end
  end

  def edit
    @rule = @rule.with_defaults
  end

  def update
    if @rule.update rule_params
      redirect_to rules_path
    end
  end

  def destroy
    @rule.destroy
    redirect_to rules_path
  end

  private

  def rule_params
    params.require(:rule).permit(
      :name, :status, :rule_type, :select_cat, :filter_cat,
      :shopify_ids, :shop_id,
      conditions_attributes: [
        :id, :_destroy, :condition_type, :condition_str
      ],
      rule_items_attributes: [
        :id, :_destroy, :shopify_id, :shopify_type, :name_1, :name_2
      ],
      price_levels_attributes: [
        :id, :_destroy, :break_number, :discount_amount, :discount_type
      ]
    )
  end

  def set_rule
    @rule = Rule.find(params[:id])
  end

  def set_nav
    @nav_str = 'PO\'s'
  end
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/rules/_form.haml
= form_for @rule do |f|
  .row
    .col-12.col-md-6
      .card
        .card-body
          .form-group
            = f.label :name, 'Rule Name'
            = f.text_field :name, placeholder: "Enter Rule Name", class: "form-control", required: true
    .col-12.col-md-6
      .card
        .card-body
          .form-group
            = f.label :status
            %div
              = f.check_box :status, "data-toggle": "toggle", "data-onstyle": "primary", "data-offstyle": "secondary"
  %br
  .row
    .col-12
      .card
        .card-body
          = f.label :rule_type, 'Rule Type'
          %div
            - Rule.rule_types.each_with_index do |rule, index|
              .form-check.form-check-inline
                = f.radio_button :rule_type, rule[0], id: "rule_type_#{index}",
                  class: 'form-check-input', disabled: @rule.persisted?
                %label.form-check-label{for: "rule_type_#{index}"}= rule[0].capitalize


  #conditional_elements
    %br
    .row
      .col-12
        .card
          .card-body
            = f.label :select_cat, 'Select products'
            %div
              .form-check.form-check-inline
                = f.radio_button :select_cat, 'select_all', id: 'select_cat_1',
                  class: 'form-check-input'
                %label.form-check-label{for: "select_cat_1"} Select All
              .form-check.form-check-inline
                = f.radio_button :select_cat, 'custom', id: 'select_cat_0',
                  class: 'form-check-input'
                %label.form-check-label{for: "select_cat_0"} Custom Selection

    #filter_cat{class: ('d-none' unless f.object.product? && f.object.custom?)}
      %br
      .row
        .col-12
          .card
            .card-body
              = f.label :filter_cat, 'Filters'
              %div
                .form-check.form-check-inline
                  = f.radio_button :filter_cat, 'filter_custom', id: 'filter_cat_0',
                    class: 'form-check-input'
                  %label.form-check-label{for: "filter_cat_0"} Custom
                .form-check.form-check-inline
                  = f.radio_button :filter_cat, 'filter_any', id: 'filter_cat_1',
                    class: 'form-check-input'
                  %label.form-check-label{for: "filter_cat_1"} Any Conditions
                .form-check.form-check-inline
                  = f.radio_button :filter_cat, 'filter_all', id: 'filter_cat_2',
                    class: 'form-check-input'
                  %label.form-check-label{for: "filter_cat_2"} All Conditions
              #conditions{class: ('d-none' unless f.object.show_conditions?)}
                = f.fields_for :conditions, @rule.conditions do |c|
                  .row.condition-item
                    .col-12.col-md-6
                      .form-group
                        = c.select :condition_type,
                          options_for_select([['Product Vendor', 'vendor'], ['Product Type', 'type'], ['Product Tag', 'tag']]),
                          {}, class: 'form-control'
                    .col-12.col-md-6
                      .form-group.d-flex.align-items-center.justify-content-between
                        = c.text_field :condition_str, placeholder: 'Type Here', class: 'form-control'
                        %i.bi.bi-trash
                    - if c.object.persisted?
                      = c.hidden_field :id
                      = c.hidden_field :_destroy, class: 'destroy'
                .row
                  .col-12
                    %span#add_new_filter.btn.btn-primary Add Condition
              / .row
              /   .col-12
              /     %span#select_products.btn.btn-primary{"data-toggle": "modal", "data-target": "#productsModal"} Select Products

    = render 'selected_objects'
    = render 'price_levels', f: f
  = f.submit

= render 'shared/products_modal'
= render 'shared/variants_modal'
= render 'shared/collections_modal'

= render 'rule_item_template'


app/views/rules/_price_levels.html.erb
<div id="price_levels">
  <br>
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div class="d-flex align-items-center justify-content-between">
            <label id="selected_label">Price Levels</label>
          </div>
          <div class="price-levels-section">
            <table class="table">
              <thead>
                <th class="col-md-2 col-lg-3">Quantity</th>
                <th class="col-md-3 col-lg-3">Discount</th>
                <th class="col-md-1 col-lg-1"></th>
                <th class="col-md-3 col-lg-5"></th>
              </thead>
              <tbody id="price-levels-body">
                <%= f.fields_for :price_levels, @rule.price_levels do |fp| %>
                  <tr>
                    <td>
                      <%= fp.number_field :break_number,
                        class: 'form-control', min: 1 %>
                      </td>
                    <td>
                      <div class="input-group discount_price_group">
                        <%= fp.number_field :discount_amount,
                          class: 'discount_price form-control discount', min: 1 %>
                        <div class="input-group-addon">
                          <%= fp.select :discount_type,
                            options_for_select([['USD (Price Discount)', 'price_discount'],
                              ['USD (Fixed Price)', 'fixed_price'], ['% Off', 'percent_discount']], fp.object.discount_type),
                              {}, class: 'form-control discount' %>
                        </div>
                      </div>
                    </td>
                    <td><i class="bi bi-trash"></i></td>
                    <td>
                      <% if fp.object.persisted? %>
                        <% if fp.object.price_discount? %>
                          Get $<%= fp.object.discount_amount %> Off on each product
                        <% elsif fp.object.fixed_price? %>
                          Get each product for $<%= fp.object.discount_amount %>
                        <% elsif fp.object.percent_discount? %>
                          Get <%= fp.object.discount_amount %>% Off on each product
                        <% end %>
                      <% end %>
                    </td>
                    <% if fp.object.persisted? %>
                      <%= fp.hidden_field :id %>
                      <%= fp.hidden_field :_destroy, class: 'destroy' %>
                    <% end %>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <div class="row">
              <div class="col-12">
                <span id="add-price-level" class="btn btn-primary">Add Price</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rules/_rule_item_template.html.erb
<template id="rule-item-template">
  <input type="hidden" class="shopify-id"
  name="rule[rule_items_attributes][NESTED_ID][shopify_id]">
  <input type="hidden" class="shopify-type"
  name="rule[rule_items_attributes][NESTED_ID][shopify_type]">
  <input type="hidden" class="name-1"
  name="rule[rule_items_attributes][NESTED_ID][name_1]">
  <input type="hidden" class="name-2"
  name="rule[rule_items_attributes][NESTED_ID][name_2]">
</template>

<template id="condition-template">
  <div class="row condition-item">
    <div class="col-12 col-md-6">
      <div class="form-group">
        <select class="form-control" name="rule[conditions_attributes][NESTED_ID][condition_type]">
          <option value="vendor">Product Vendor</option>
          <option value="type">Product Type</option>
          <option value="tag">Product Tag</option>
        </select>
      </div>
    </div>
    <div class="col-12 col-md-6">
      <div class="form-group d-flex align-items-center justify-content-between">
        <input placeholder="Type Here" class="form-control" type="text"
          name="rule[conditions_attributes][NESTED_ID][condition_str]">
        <i class="bi bi-trash"></i>
      </div>
    </div>
  </div>
</template>

<template id="price-level-template">
  <tr>
    <td>
      <input class="form-control" min="1" type="number"
        name="rule[price_levels_attributes][NESTED_ID][break_number]">
    </td>
    <td>
      <div class="input-group discount_price_group">
        <input class="discount_price form-control discount" min="1" type="number"
          name="rule[price_levels_attributes][NESTED_ID][discount_amount]">
        <div class="input-group-addon">
          <select class="form-control discount"
            name="rule[price_levels_attributes][NESTED_ID][discount_type]">
            <option value="price_discount">USD (Price Discount)</option>
            <option value="fixed_price">USD (Fixed Price)</option>
            <option value="percent_discount">% Off</option>
          </select>
        </div>
      </div>
    </td>
    <td><i class="bi bi-trash"></i></td>
    <td></td>
  </tr>
</template>

app/views/rules/_selected_objects.html.erb
<div id="selected_objects" class="<%= 'd-none' unless @rule.show_selected_objects? %>">
  <br>
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div class="d-flex align-items-center justify-content-between">
            <label id="selected_label">Selected Products</label>
            <div>
              <span id="select-products" class="btn btn-primary"
                data-toggle="modal" data-target="#productsModal">
                Select Products
              </span>
              <span id="select-variants" class="btn btn-primary d-none"
                data-toggle="modal" data-target="#variantsModal">
                Select Variants
              </span>
              <span id="select-collections" class="btn btn-primary d-none"
                data-toggle="modal" data-target="#collectionsModal">
                Select Collections
              </span>
            </div>
          </div>
          <div class="selected-objects-section">
            <table class="table">
              <thead>
                <% if @rule.product? %>
                  <th class="col-md-10">Product Name</th>
                  <th class="col-md-2">Action</th>
                <% elsif @rule.variant? %>
                  <th class="col-md-6">Product Name</th>
                  <th class="col-md-4">Variant Name</th>
                  <th class="col-md-2">Action</th>
                <% elsif @rule.collection? %>
                  <th class="col-md-10">Collection Name</th>
                  <th class="col-md-2">Action</th>
                <% end %>
              </thead>
              <tbody id="selected-objects-body">
                <% @rule.rule_items.each_with_index do |rule_item, index| %>
                  <tr data-id="<%= rule_item.shopify_id %>">
                    <td><%= rule_item.name_1 %></td>
                    <% if @rule.product? %>
                    <% elsif @rule.variant? %>
                      <td><%= rule_item.name_2 %></td>
                    <% elsif @rule.collection? %>
                    <% end %>
                    <td><span class="btn btn-small btn-danger object-remove">Remove</span></td>
                    <input type="hidden"
                      name="rule[rule_items_attributes][<%= index %>][id]"
                      value="<%= rule_item.id %>">
                    <input type="hidden" class="shopify-destroy"
                      name="rule[rule_items_attributes][<%= index %>][_destroy]"
                      value="false">
                    <input type="hidden" class="shopify-id"
                      name="rule[rule_items_attributes][<%= index %>][shopify_id]"
                      value="<%= rule_item.shopify_id %>">
                    <input type="hidden" class="shopify-type"
                      name="rule[rule_items_attributes][<%= index %>][shopify_type]"
                      value="<%= rule_item.shopify_type %>">
                    <input type="hidden" class="name-1" value="<%= rule_item.name_1 %>"
                      name="rule[rule_items_attributes][<%= index %>][name_1]">
                    <input type="hidden" class="name-2" value="<%= rule_item.name_2 %>"
                      name="rule[rule_items_attributes][<%= index %>][name_2]">
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rules/edit.html.erb
<h1>
  Edit Rule
</h1>
<%= render 'form' %>

app/views/rules/index.haml
.d-flex.justify-content-end
  =link_to "Add New", new_rule_path, class: "d-block d-md-inline-block btn btn-primary"
%hr

- if @rules.present?
  %table.table.table-striped
    %thead.thead-dark
      %tr
        %th{scope: "col"} Rule Name
        %th{scope: "col"} Rule Type
        %th{scope: "col"} Action
        %th{scope: "col"} Status
    %tbody
      - @rules.each do |rule|
        %tr
          %td= rule.name
          %td= rule.rule_type
          %td
            .action-buttons.d-inline-flex.align-items-center
              = link_to edit_rule_path(rule) do
                %i.bi.bi-pencil
              %i.bi.bi-stickies.d-none
              = link_to rule_path(rule), method: :delete,
                data: { confirm: 'Are you sure to delete?' }, style: 'color: #dc3545;' do
                %i.bi.bi-trash
          %td
            %input{ type: "checkbox", checked: (true if rule.status), disabled: true}
- else
  No rules

= will_paginate @products, :params => {:page => params[:page]}

app/views/rules/new.haml
%h1 Add New Rule
= render 'form'