config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
# frozen_string_literal: true

namespace :app_proxy do
  root action: 'index'
  # simple routes without a specified controller will go to AppProxyController

  # more complex routes will go to controllers in the AppProxy namespace
  #   resources :reviews
  # GET /app_proxy/reviews will now be routed to
  # AppProxy::ReviewsController#index, for example
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/search_products' => 'home#search_products'
  get '/search_variants' => 'home#search_variants'
  get '/search_collections' => 'home#search_collections'
  get '/api/product' => 'api#product'
  get '/api/multi-products' => 'api#multi_products'
  get '/api/filter_options' => 'api#filter_options'
  post '/api/draft-order' => 'api#draft_order'
  post '/api/cart' => 'api#cart'

  resources :installation
  resources :rules
  resources :suppliers do
    member do
      get :status
      get :get_sub_brands
    end
  end
  resources :products do
    collection do
      get :missing
    end
  end
  resources :variants
  resources :orders
  resources :purchase_orders do
    collection do
      get :create_po
    end
    member do
      post :append_draft_order
      put :complete_draft_order
    end
  end
  resources :purchase_order_items do
    member do
      get :send_invoice
      get :download_pdf
      get :render_pdf
    end
  end
  resource :settings, only: %i(show update)
end

app/models/product.rb
class Product < ApplicationRecord
	validates_uniqueness_of :shopify_id
  belongs_to :shop, optional: true
  has_many :variants, dependent: :destroy
  has_many :product_options, dependent: :destroy

  has_many :collection_products, dependent: :destroy
  has_many :collections, through: :collection_products

  self.per_page = 50

  def self.save_shopify(sproduct, object_type='webhook')
  	product_data = Product.make_data(sproduct, object_type)
    product = Product.find_or_create_by(shopify_id: product_data[:shopify_id])
    if product.present?
    	if product_data[:title].present?
    		product.update product_data
	    	product.update_variants(sproduct, object_type)
	    	product.update_options(sproduct, object_type)
	    else
	    	product.destroy
    	end
    end
	end

	def self.make_data(sproduct, object_type='webhook')
		if object_type=='api'
  		product_data = {
  			shopify_id: sproduct.id,
    		handle: sproduct.handle,
    		featured_image: sproduct.images&.first&.src,
      	title: sproduct.title,
      	tags: sproduct.tags,
      	vendor: sproduct.vendor,
      	product_type: sproduct.product_type,
      	published_scope: sproduct.published_scope,
      	body_html: sproduct.body_html,
      	published_at: sproduct.published_at,
      	p_created_at: sproduct.created_at,
      	p_updated_at: sproduct.updated_at,
      	shop_id: Shop.first.id
  		}
  	else
  		product_data = {
  			shopify_id: sproduct['id'],
    		handle: sproduct['handle'],
    		featured_image: (sproduct['images'].present? ? sproduct['images'][0]['src'] : nil),
      	title: sproduct['title'],
      	tags: sproduct['tags'],
      	vendor: sproduct['vendor'],
      	product_type: sproduct['product_type'],
      	published_scope: sproduct['published_scope'],
      	body_html: sproduct['body_html'],
      	published_at: sproduct['published_at'],
      	p_created_at: sproduct['created_at'],
      	p_updated_at: sproduct['updated_at'],
      	shop_id: Shop.first.id
  		}
  	end
  	product_data
	end

	def update_variants(sproduct, object_type)
		variant_ids = []
		origin_ids = self.variants.pluck(:id)
		if object_type=='api'
			sproduct.variants.each do |s_variant|
				variant = Variant.find_or_create_by(shopify_id: s_variant.id)
				if variant.present?
					variant.update(
						shopify_product_id: sproduct.id,
			    	title: s_variant.title,
			    	price: s_variant.price&.to_f,
			    	compare_at_price: s_variant.compare_at_price&.to_f,
			    	sku: s_variant.sku,
			    	inventory_policy: s_variant.inventory_policy,
			    	fulfillment_service: s_variant.fulfillment_service,
			    	inventory_management: s_variant.inventory_management,
			    	option_1: s_variant.option1,
			    	option_2: s_variant.option2,
			    	option_3: s_variant.option3,
			    	barcode: s_variant.barcode,
			      inventory_item_id: s_variant.inventory_item_id,
			      shop_id: Shop.first.id,
			      product: self
					)
					variant_ids << variant.id
				end
			end if sproduct.variants.present?
		else
			sproduct['variants'].each do |s_variant|
				variant = Variant.find_or_create_by(shopify_id: s_variant['id'])
				if variant.present?
					variant.update(
						shopify_product_id: sproduct['id'],
			    	title: s_variant['title'],
			    	price: s_variant['price']&.to_f,
			    	compare_at_price: s_variant['compare_at_price']&.to_f,
			    	sku: s_variant['sku'],
			    	inventory_policy: s_variant['inventory_policy'],
			    	fulfillment_service: s_variant['fulfillment_service'],
			    	inventory_management: s_variant['inventory_management'],
			    	option_1: s_variant['option1'],
			    	option_2: s_variant['option2'],
			    	option_3: s_variant['option3'],
			    	barcode: s_variant['barcode'],
			      inventory_item_id: s_variant['inventory_item_id'],
			      shop_id: Shop.first.id,
			      product: self
					)
					variant_ids << variant.id
				end
			end if sproduct['variants'].present?
		end
		self.variant_ids = variant_ids
		origin_ids = origin_ids - variant_ids
		Variant.where(id: origin_ids).destroy_all if origin_ids.present?
	end

	def variants_data
		self.variants.map do |variant|
      item = variant.slice :shopify_id, :inventory_available,
        :min_item_order_qty, :max_item_order_qty, :item_qty_per_case
      item[:price_levels] = []
      variant.price_levels.order(item_qty: :asc).each do |price_level|
        next if price_level.item_qty.blank? || price_level.item_sale_price.blank?
        sub_item = {
          item_qty: price_level.item_qty,
          item_sale_price: price_level.item_sale_price.to_f,
          item_total_markup_cost: price_level.item_sale_price.to_f * price_level.item_qty
        }
        item[:price_levels] << sub_item
      end
      item[:price_levels] << {item_qty: 1, item_total_markup_cost: variant.price, item_sale_price: variant.price} if item[:price_levels].blank?
      item
    end
	end

	def update_options(sproduct, object_type)
		option_ids = []
		origin_ids = self.product_options.pluck(:id)
		if object_type=='api'
			sproduct.options.each do |s_option|
				option = ProductOption.find_or_create_by(shopify_id: s_option.id)
				if option.present?
					option.update(
						shopify_product_id: s_option.product_id,
			    	position: s_option.position,
			    	option_name: s_option.name,
			    	option_values: s_option.values,
			      shop_id: Shop.first.id,
			      product: self
					)
					option_ids << option.id
				end
			end if sproduct.options.present?
		else
			sproduct['options'].each do |s_option|
				option = ProductOption.find_or_create_by(shopify_id: s_option['id'])
				if option.present?
					option.update(
						shopify_product_id: s_option['product_id'],
			    	position: s_option['position'],
			    	option_name: s_option['name'],
			    	option_values: s_option['values'],
			      shop_id: Shop.first.id,
			      product: self
					)
					option_ids << option.id
				end
			end if sproduct['options'].present?
		end
		self.product_option_ids = option_ids
		origin_ids = origin_ids - option_ids
		ProductOption.where(id: origin_ids).destroy_all if origin_ids.present?
	end

	def product_card_info
		v_data = self.variants_data
		min_price = 10000000
		max_price = 0
		v_data.each do |v|
			v[:price_levels].each do |p_level|
				if p_level[:item_sale_price] > max_price
					max_price = p_level[:item_sale_price]
				end
				if p_level[:item_sale_price] < min_price
					min_price = p_level[:item_sale_price]
				end
			end
		end
		{
			min_item_order_qty: v_data.map {|v| (v[:min_item_order_qty] || 1) }.min,
			min_price: min_price,
			max_price: max_price
		}
	end

	def shopify_url
		"https://#{Shop.first.shopify_domain}/admin/products/#{self.shopify_id}"
	end

	def product_url
		"https://#{Shop.first.shopify_domain}/products/#{self.handle}"
	end

  def vendor_names
    Vendor.where(id: variants.pluck(:vendor_ids).flatten).pluck(:company_name)
  end

  def vendor_brands
    Vendor.where(id: variants.pluck(:vendor_ids).flatten)
      .pluck(:sub_brands).flatten.uniq
  end

  def variant_brands
    variants.pluck(:vender_sub_brands).flatten.uniq
  end
end

app/controllers/products_controller.rb
require 'csv'

class ProductsController < AuthenticatedController
  before_action :set_nav
  before_action :set_products, only: [:index, :missing]
  skip_before_action :verify_authenticity_token, only: :create

  def index
    @products = @products.where.not(published_at: nil).order('products.title' => 'asc')
      .paginate(page: (params[:page] || 1))
    file = File.read 'upload.json'
    @json_variants = JSON.parse(file)
  end

  def edit
  end

  def update
  end

  def create
    # file = params[:attachment].read
    # @json_variants = JSON.parse(file)
    # puts @json_variants
    # respond_to do |format|
    #   format.js { render layout: false}
    # end
    
    csv_variants = CSV.parse(params[:file].read, headers: true)
    csv_variants.each do |csv_variant|
      product = Product.find_by_shopify_id csv_variant['Shopify Product ID']
      sku = csv_variant['Shopify SKU/Variant SKU'].presence || csv_variant['Shopify SKU']
      if product.present?
        variant = product.variants.find_by_sku sku
      else
        variant = Variant.find_by_sku sku
      end
      variant.update_from_csv csv_variant if variant.present?
    end

    redirect_to products_path
  end

  def missing
    missing_vendor_variant_ids = Variant.all.pluck(:vendor_ids, :id)&.select {|variant| variant[0].reject(&:blank?).blank?}&.map {|variant| variant[1]}
    price_error_variant_ids = PriceLevel.all.pluck(:id, :item_qty, :item_wholesale_cost, :item_sale_price, :variant_id)&.select {|pl| pl[1].blank? || pl[2].blank? || pl[3].blank?}&.map {|pl| pl[4]}
    price_missing_variant_ids = Variant.all.pluck(:id) - PriceLevel.all.pluck(:variant_id)&.uniq
    variant_ids = (missing_vendor_variant_ids + price_error_variant_ids + price_missing_variant_ids).uniq
    product_ids = Variant.where(id: variant_ids).pluck(:product_id)&.uniq

    @products = @products.where(id: product_ids).where.not(published_at: nil).order('products.title' => 'asc')
      .paginate(page: (params[:page] || 1))
    file = File.read 'upload.json'
    @json_variants = JSON.parse(file)
  end

  private

  def set_nav
    @nav_str = 'Products'
  end

  def set_product
    # @product = Product.find params[:id]
  end

  def set_products
    @keyword = params[:keyword]&.strip
    @products = Product.all
    return if params[:keyword].blank?
    query = "products.title like ? OR products.shopify_id like ? OR"\
      " products.vendor like ? OR products.product_type like ?"
    query += "OR variants.sku like ? OR variants.shopify_id like ?"
    key = "%#{@keyword}%"
    # @products = @products.joins(:variants).where query, key, key, key, key, key, key
    product_ids = @products.joins(:variants)
      .where(query, key, key, key, key, key, key)
      .pluck(:id)
    @products = @products.where id: product_ids
  end
end

app/views/products/_products_modal.html.erb
<div class="modal fade" id="uploadModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="uploadModalLabel">
          Upload Variants
        </h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <table>
        <thead>
          <th>Shopify ID</th>
          <th>Title</th>
          <th>Supplier Type</th>
          <th>Suppliers</th>
          <th>Production Details</th>
          <th>Pricing</th>
        </thead>
        <tbody>
          <% @json_variants.each do |json_variant| %>
            <tr>
              <td><%= json_variant['shopify_id'] %></td>
              <td></td>
              <td><%= json_variant['supplier_type'] %></td>
              <td>
                <% json_variant['suppliers'].each do |supplier| %>
                  <div style="border: 1px solid #ccc; margin-bottom: 5px;">
                    <p>Name: <%= supplier['name'] %></p>
                    <p>Brand: <%= supplier['brand'] %></p>
                    <p>Type: <%= supplier['type'] %></p>
                  </div>
                <% end %>
              </td>
              <td>
                <p>Variant Size: <%= json_variant['production_details']['size'] %></p>
                <p>Variant Color: <%= json_variant['production_details']['color'] %></p>
                <p>Supplier Product Name: <%= json_variant['production_details']['supplier_product_name'] %></p>
                <p>Supplier SKU: <%= json_variant['production_details']['supplier_sku'] %></p>
                <p>One Time Setup Fee: <%= json_variant['production_details']['one_time_setup_fee'] %></p>
                <p>Recurring/Re-Order Fee: <%= json_variant['production_details']['recurring_reorder_fee'] %></p>
                <p>Quote Number: <%= json_variant['production_details']['quote_number'] %></p>
                <p>Supplier Proof Link: <%= json_variant['production_details']['supplier_proof_link'] %></p>
                <p>Proof Photo Link: <%= json_variant['production_details']['proof_photo_link'] %></p>
                <p>Artwork/Vector Logo URL: <%= json_variant['production_details']['artwork_url'] %></p>
                <p>Decoration Location: <%= json_variant['production_details']['decoration_location'] %></p>
                <p>Decoration Type: <%= json_variant['production_details']['decoration_type'] %></p>
                <p>Logo Name: <%= json_variant['production_details']['logo_name'] %></p>
                <p>Logo Color: <%= json_variant['production_details']['logo_color'] %></p>
                <p>Logo Size: <%= json_variant['production_details']['logo_size'] %></p>
                <p>Inventory on Hand: <%= json_variant['production_details']['inventory_on_hand'] %></p>
                <p>Enforced Multiple Quantity: <%= json_variant['production_details']['enforced_multiple_quantity'] %></p>
                <p>Base Lead Time: <%= json_variant['production_details']['base_lead_time'] %></p>
                <p>Start Production: <%= json_variant['production_details']['start_production'] %></p>
                <p>Lead Time in Days: <%= json_variant['production_details']['lead_time_in_days'] %></p>
                <p>Additional Lead Time: <%= json_variant['production_details']['additional_lead_time'] %></p>
                <p>Different cost based on quantity: <%= json_variant['production_details']['different_cost_based_on_quantity'] %></p>
                <p>Ship To: <%= json_variant['production_details']['ship_to'] %></p>
                <p>Supplier Decoration or Blank Product: <%= json_variant['production_details']['supplier_decoration'] %></p>
                <p>Blank Decorator: <%= json_variant['production_details']['blank_docorator'] %></p>
                <p>DST File: <%= json_variant['production_details']['dst_file'] %></p>
                <p>SU Comp: <%= json_variant['production_details']['su_comp'] %></p>
                <p>Proof Required: <%= json_variant['production_details']['proof_required'] %></p>
              </td>
              <td>
                
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      </div>
      <div class="modal-footer justify-content-between"></div>
    </div>
  </div>
</div>

<style type="text/css">
  .modal-dialog {
    max-width: 90%;
  }

  table {
    width: 100%;
  }

  table tr {
    border-bottom: 1px dotted #aaa;
  }

  table tr td {
    padding: 0 5px;
  }
</style>

app/views/products/_variant_item.html.erb
<table>
  <thead>
    <th>Shopify ID</th>
    <th>Title</th>
    <th>Supplier Type</th>
    <th>Suppliers</th>
    <th>Production Details</th>
    <th>Pricing</th>
  </thead>
  <tbody>
    
  </tbody>
</table>

app/views/products/create.js.erb
$('#uploadModal').modal("show")
<% @json_variants.each do |json_variant| %>
<% end %>

app/views/products/edit.html.erb
<div id="rule-content">
  <div class="row">
    <div class="col-md-3">
      <div>Variants</div>
      <% @product.variants.each do |variant| %>
        <div><%= variant.title %></div>
      <% end %>
    </div>
    <div class="col-md-9">
      <div class="card">
        <div class="card-body">
          <h4>Product Details</h4>
          <div class="row">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="row" style="margin: 10px 0 30px;">
  <div class="col-sm-8">
    <!-- <span id="upload-products" class="btn btn-primary"
      data-toggle="modal" data-target="#upload-products-modal">
      Upload Products
    </span> -->
    <%= form_tag products_path, id: 'upload-form', multipart: true do %>
      <label id="upload-products" class="btn btn-primary">
        Upload Products
        <input type="file" name="file" id="file" class="d-none" accept=".csv">
      </label>
      <%= link_to 'Products with Missing Data', missing_products_path, class: "btn btn-secondary" %> 
    <% end %>
  </div>
  <div class="col-sm-4">
    <%= form_tag products_path, method: :get do %>
      <input name="keyword" class="form-control"
        placeholder="Search" style="font-size: 18px;" value="<%= @keyword %>">
    <% end %>
  </div>
</div>
<% if @products.present? %>
  <% @products.each do |product| %>
    <div class="product-item">
      <div class="row product">
        <div class="col-sm-1">
          <i class="bi bi-chevron-down toggle-variant"></i>
        </div>
        <div class="col-sm-1">
          <% if product.featured_image.present? %>
            <img src="<%= product.featured_image %>">
          <% end %>
        </div>
        <div class="col-sm-4">
          <%= product.title %>
          <br>
          <a href="https://jpmc.keeperscollective.com/products/<%= product.handle %>" target="_blank">View Product</a>
        </div>
        <div class="col-sm-3">
          <% product.vendor_names.each do |vendor_name| %>
            <p><%= vendor_name %></p>
          <% end %>
        </div>
        <div class="col-sm-3">
          <% product.variant_brands.each do |variant_brand| %>
            <p><%= variant_brand %></p>
          <% end %>
        </div>
      </div>
      <div class="variant-items d-none">
        <% product.variants.each do |variant| %>
          <div class="row variant-item">
            <div class="col-sm-4 offset-sm-2">
              <%= variant.title == 'Default Title' ? product.title : variant.title %>
            </div>
            <div class="col-sm-4">
              <%= variant.sku %>
            </div>
            <div class="col-sm-2">
              <%= link_to edit_variant_path(variant) do %>
                <i class="bi bi-pencil"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
<% else %>
  No products
<% end %>

<%= will_paginate @products, params: {page: params[:page]} %>


<style>
  .product-item .product {
    align-items: center;
    border: 1px solid #bbb;
    margin: 10px;
  }

  .product-item .product img {
    width: 100%;
  }

  .variant-item {
    margin: 5px 10px;
    padding: 10px 0px;
    border: 1px solid #ddd;
  }

  .variant-item a {
    float: right;
  }

  p {
    margin: 2px 0;
  }
</style>

<%= render 'products_modal' %>

app/views/products/missing.html.erb
<div class="row" style="margin: 10px 0 30px;">
  <div class="col-sm-8">
    <!-- <span id="upload-products" class="btn btn-primary"
      data-toggle="modal" data-target="#upload-products-modal">
      Upload Products
    </span> -->
    <%= form_tag products_path, id: 'upload-form', multipart: true do %>
      <label id="upload-products" class="btn btn-primary">
        Upload Products
        <input type="file" name="file" id="file" class="d-none" accept=".csv">
      </label>
      <%= link_to 'Go to all products', products_path, class: "btn btn-secondary" %> 
    <% end %>
  </div>
  <div class="col-sm-4">
    <%= form_tag missing_products_path, method: :get do %>
      <input name="keyword" class="form-control"
        placeholder="Search" style="font-size: 18px;" value="<%= @keyword %>">
    <% end %>
  </div>
</div>
<% if @products.present? %>
  <% @products.each do |product| %>
    <div class="product-item">
      <div class="row product">
        <div class="col-sm-1">
          <i class="bi bi-chevron-down toggle-variant"></i>
        </div>
        <div class="col-sm-1">
          <% if product.featured_image.present? %>
            <img src="<%= product.featured_image %>">
          <% end %>
        </div>
        <div class="col-sm-4">
          <%= product.title %>
          <br>
          <a href="https://jpmc.keeperscollective.com/products/<%= product.handle %>" target="_blank">View Product</a>
        </div>
        <div class="col-sm-3">
          <% product.vendor_names.each do |vendor_name| %>
            <p><%= vendor_name %></p>
          <% end %>
        </div>
        <div class="col-sm-3">
          <% product.variant_brands.each do |variant_brand| %>
            <p><%= variant_brand %></p>
          <% end %>
        </div>
      </div>
      <div class="variant-items d-none">
        <% product.variants.each do |variant| %>
          <div class="row variant-item">
            <div class="col-sm-4 offset-sm-2">
              <%= variant.title %>
            </div>
            <div class="col-sm-4">
              <%= variant.sku %>
            </div>
            <div class="col-sm-2">
              <%= link_to edit_variant_path(variant) do %>
                <i class="bi bi-pencil"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
<% else %>
  No products
<% end %>

<%= will_paginate @products, params: {page: params[:page]} %>


<style>
  .product-item .product {
    align-items: center;
    border: 1px solid #bbb;
    margin: 10px;
  }

  .product-item .product img {
    width: 100%;
  }

  .variant-item {
    margin: 5px 10px;
    padding: 10px 0px;
    border: 1px solid #ddd;
  }

  .variant-item a {
    float: right;
  }

  p {
    margin: 2px 0;
  }
</style>

<%= render 'products_modal' %>